# Generated by Django 6.0.3 on 2026-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student_name', models.CharField(help_text='First name or nickname only', max_length=100)),
                ('class_name', models.CharField(help_text='Example: 7A', max_length=50)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('media_file', models.FileField(upload_to='submissions/')),
                ('parent_approval', models.BooleanField(default=False, help_text='Parent permission confirmed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
